name: Testes Automatizados (CRUD Posts)

on: 
  push:
      branches:
        - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Configurar Node.js
      uses: actions/setup-node@v2
      with:
        node-version: "18"

    - name: Executar install e test
      run: |
        npm install
        npm run test